--## 0. Database setup
CREATE DATABASE CDSA;
USE CDSA;

--## 1. Table Rol
CREATE TABLE ROL (
    ID_ROL INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (255)
);

-- ## 2. Table Usuario
CREATE TABLE USUARIO (
    ID_USUARIO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_ROL INTEGER NOT NULL,
    NOMBRE VARCHAR (255) NOT NULL,
    ACTIVO CHAR (10) NOT NULL
);

-- ## 4. Foreing key Usuario
ALTER TABLE USUARIO
ADD FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL);

-- ## 6. Fill Table Rol
INSERT INTO ROL VALUES (1, 'ADMINISTRADOR'), (2, 'AUDITOR'), (3, 'AUXILIAR');